/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Administrator' at '16-9-20 下午10:04' with Gradle 3.1
 *
 * @author Administrator, @date 16-9-20 下午10:04
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
